In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("MRegularSeasonDetailedResults.csv")
df.head

<bound method NDFrame.head of         Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT  WFGM  \
0         2003      10     1104      68     1328      62    N      0    27
1         2003      10     1272      70     1393      63    N      0    26
2         2003      11     1266      73     1437      61    N      0    24
3         2003      11     1296      56     1457      50    N      0    18
4         2003      11     1400      77     1208      71    N      0    30
...        ...     ...      ...     ...      ...     ...  ...    ...   ...
118877    2025     132     1196      86     1397      77    N      0    26
118878    2025     132     1272      84     1412      72    N      0    32
118879    2025     132     1276      59     1458      53    N      0    19
118880    2025     132     1433      68     1206      63    N      0    19
118881    2025     132     1463      90     1165      84    N      0    31

        WFGA  ...  LFGA3  LFTM  LFTA  LOR  LDR  LAst  LTO  LStl  LBlk  LPF
0         58  ...     10    16    22   10   22     8   18     9     2   20
1         62  ...     24     9    20   20   25     7   12     8     6   16
2         58  ...     26    14    23   31   22     9   12     2     5   23
3         38  ...     22     8    15   17   20     9   19     4     3   23
4         61  ...     16    17    27   21   15    12   10     7     1   14
...      ...  ...    ...   ...   ...  ...  ...   ...  ...   ...   ...  ...
118877    61  ...     26    25    32    5   20    15    9     7     5   21
118878    68  ...     27    17    23   21   23    10   15     5     4   21
118879    59  ...     39    16    18   15   31     8    6     3     2   14
118880    47  ...     21    16    19   14   19    13   11    11     3   22
118881    62  ...     27    15    16    4   26    15   11     2     2   16

[118882 rows x 34 columns]>

In [4]:
# Basic EDA of team stats

# since basketball teams evolved/changed a lot since the start I only want to use more recent data for each team
df = df[df['Season'] > 2024]

# create database of just team stats
df_team_stats = df.drop(columns = ['Season', 'DayNum', 'WLoc', 'NumOT'])
df_team_stats

,WTeamID,WScore,LTeamID,LScore,WFGM,WFGA,WFGM3,WFGA3,WFTM,WFTA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
113241,1104,110,1421,54,38,60,8,18,26,37,...,26,8,14,13,12,8,8,6,2,22
113242,1112,93,1145,64,33,68,8,28,19,27,...,26,10,13,4,18,12,19,7,1,20
113243,1117,80,1103,75,34,73,9,30,3,6,...,34,9,13,16,30,19,14,9,3,11
113244,1119,67,1107,59,22,50,5,17,18,28,...,24,11,16,5,25,11,9,8,2,24
113245,1130,69,1154,60,21,54,5,18,22,28,...,24,17,25,8,21,11,14,8,5,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118877,1196,86,1397,77,26,61,9,27,25,28,...,26,25,32,5,20,15,9,7,5,21
118878,1272,84,1412,72,32,68,6,13,14,23,...,27,17,23,21,23,10,15,5,4,21
118879,1276,59,1458,53,19,59,9,33,12,13,...,39,16,18,15,31,8,6,3,2,14
118880,1433,68,1206,63,19,47,8,25,22,27,...,21,16,19,14,19,13,11,11,3,22
118881,1463,90,1165,84,31,62,13,23,15,21,...,27,15,16,4,26,15,11,2,2,16

In [7]:
# Run significance test between winner and loser variables to see which ones have significant differences
from scipy import stats

t_statistic, p_value = stats.ttest_ind(df['WScore'], df['LScore'])
print("Score: ", f"T-statistic: {t_statistic}, P-value: {p_value}")

t_statistic, p_value = stats.ttest_ind(df['WFGM'], df['LFGM'])
print("FGM: ", f"T-statistic: {t_statistic}, P-value: {p_value}")

t_statistic, p_value = stats.ttest_ind(df['WFGA'], df['LFGA'])
print("FGA: ", f"T-statistic: {t_statistic}, P-value: {p_value}")

t_statistic, p_value = stats.ttest_ind(df['WFGM3'], df['LFGM3'])
print("FGM3: ", f"T-statistic: {t_statistic}, P-value: {p_value}")

t_statistic, p_value = stats.ttest_ind(df['WFGA3'], df['LFGA3'])
print("FGMA3: ", f"T-statistic: {t_statistic}, P-value: {p_value}")

t_statistic, p_value = stats.ttest_ind(df['WFTM'], df['LFTM'])
print("FTM: ", f"T-statistic: {t_statistic}, P-value: {p_value}")

t_statistic, p_value = stats.ttest_ind(df['WFTA'], df['LFTA'])
print("FTA: ", f"T-statistic: {t_statistic}, P-value: {p_value}")

t_statistic, p_value = stats.ttest_ind(df['WOR'], df['LOR'])
print("OR: ", f"T-statistic: {t_statistic}, P-value: {p_value}")

t_statistic, p_value = stats.ttest_ind(df['WDR'], df['LDR'])
print("DR: ", f"T-statistic: {t_statistic}, P-value: {p_value}")

t_statistic, p_value = stats.ttest_ind(df['WAst'], df['LAst'])
print("Ast: ", f"T-statistic: {t_statistic}, P-value: {p_value}")

t_statistic, p_value = stats.ttest_ind(df['WTO'], df['LTO'])
print("TO: ", f"T-statistic: {t_statistic}, P-value: {p_value}")

t_statistic, p_value = stats.ttest_ind(df['WStl'], df['LStl'])
print("Stl: ", f"T-statistic: {t_statistic}, P-value: {p_value}")

t_statistic, p_value = stats.ttest_ind(df['WBlk'], df['LBlk'])
print("Blk: ", f"T-statistic: {t_statistic}, P-value: {p_value}")

t_statistic, p_value = stats.ttest_ind(df['WPF'], df['LPF'])
print("PF: ", f"T-statistic: {t_statistic}, P-value: {p_value}")

Score:  T-statistic: 62.01644815492613, P-value: 0.0
FGM:  T-statistic: 48.4576809877143, P-value: 0.0
FGA:  T-statistic: -2.1153406703321647, P-value: 0.03442278389029718
FGM3:  T-statistic: 24.710739545257464, P-value: 2.4524016089512336e-131
FGMA3:  T-statistic: -2.228300474804388, P-value: 0.025880119094621967
FTM:  T-statistic: 26.32589224853152, P-value: 2.76445975391753e-148
FTA:  T-statistic: 22.169434879854805, P-value: 1.258492382573989e-106
OR:  T-statistic: 5.6196607491728, P-value: 1.9587120915694087e-08
DR:  T-statistic: 46.63599245234269, P-value: 0.0
Ast:  T-statistic: 43.50201112673711, P-value: 0.0
TO:  T-statistic: -17.107575267525043, P-value: 8.531169821763625e-65
Stl:  T-statistic: 17.155425092663386, P-value: 3.826961689242791e-65
Blk:  T-statistic: 21.526816152908506, P-value: 9.161180225241704e-101
PF:  T-statistic: -18.8177734399875, P-value: 8.344863121262122e-78

In [9]:
# Being very strict with the p-values, drop less significant columns

df_sig_team_stats = df_team_stats.drop(columns = ['WFGA', 'LFGA', 'WFGA3', 'LFGA3', 'WOR', 'LOR', 'WStl', 'LStl'])
df_sig_team_stats

,WTeamID,WScore,LTeamID,LScore,WFGM,WFGM3,WFTM,WFTA,WDR,WAst,...,WPF,LFGM,LFGM3,LFTM,LFTA,LDR,LAst,LTO,LBlk,LPF
113241,1104,110,1421,54,38,8,26,37,40,21,...,12,20,6,8,14,12,8,8,2,22
113242,1112,93,1145,64,33,8,19,27,25,20,...,15,22,10,10,13,18,12,19,1,20
113243,1117,80,1103,75,34,9,3,6,33,14,...,10,28,10,9,13,30,19,14,3,11
113244,1119,67,1107,59,22,5,18,28,29,11,...,18,22,4,11,16,25,11,9,2,24
113245,1130,69,1154,60,21,5,22,28,28,10,...,21,20,3,17,25,21,11,14,5,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118877,1196,86,1397,77,26,9,25,28,24,11,...,25,22,8,25,32,20,15,9,5,21
118878,1272,84,1412,72,32,6,14,23,27,13,...,18,24,7,17,23,23,10,15,4,21
118879,1276,59,1458,53,19,9,12,13,34,14,...,16,15,7,16,18,31,8,6,2,14
118880,1433,68,1206,63,19,8,22,27,25,10,...,20,19,9,16,19,19,13,11,3,22
118881,1463,90,1165,84,31,13,15,21,20,15,...,17,29,11,15,16,26,15,11,2,16

In [11]:
# get all the unique teams and put into dataframe with each teams average

unique_teams = pd.unique(df_sig_team_stats[['WTeamID', 'LTeamID']].values.ravel('K'))
unique_teams

avg_stats = [ 'WScore', 'LScore', 'WFGM', 'WFGM3', 'WFTM',
       'WFTA', 'WDR', 'WAst', 'WTO', 'WBlk', 'WPF', 'LFGM', 'LFGM3', 'LFTM',
       'LFTA', 'LDR', 'LAst', 'LTO', 'LBlk', 'LPF']

temp_df = pd.DataFrame(columns = ['Team', 'Score' ,'FGM', 'FGM3', 'FTM','FTA', 'DR', 'Ast', 'TO', 'Blk', 'PF'])

for team in unique_teams:
    # Add where team in unique teams wins
    team_wins_df = df_sig_team_stats[df_sig_team_stats['WTeamID'] == team]
    for _, row in team_wins_df.iterrows():
        temp_df.loc[len(temp_df)] = [team, row['WScore'], row['WFGM'], row['WFGM3'], row['WFTM'], row['WFTA'],
                                     row['WDR'], row['WAst'], row['WTO'], row['WBlk'], row['WPF']]
    
    # Add where team in unique teams loses
    team_losses_df = df_sig_team_stats[df_sig_team_stats['LTeamID'] == team]
    for _, row in team_losses_df.iterrows():
        temp_df.loc[len(temp_df)] = [team, row['LScore'], row['LFGM'], row['LFGM3'], row['LFTM'], row['LFTA'],
                                     row['LDR'], row['LAst'], row['LTO'], row['LBlk'], row['LPF']]

# Print final df to see if there are the correct number of rows (thank god there are)
print(temp_df)

# Calculate the average for each team
team_avg_df = temp_df.groupby('Team').mean()

       Team  Score  FGM  FGM3  FTM  FTA  DR  Ast  TO  Blk  PF
0      1104    110   38     8   26   37  40   21  10    6  12
1      1104     88   27     6   28   44  36   13  10    4  24
2      1104     72   22    11   17   24  22   16  13    5  12
3      1104    100   39    11   11   13  30   23   7    6  17
4      1104     85   22    11   30   41  26   14  14    6  25
...     ...    ...  ...   ...  ...  ...  ..  ...  ..  ...  ..
11277  1271     62   20     3   19   25  22    6  15    1  20
11278  1271     68   23     7   15   25  14   16  14    2  25
11279  1271     72   26    10   10   14  19   16  11    6  25
11280  1271     68   21     8   18   23  15   11  16    1  22
11281  1271     70   25    11    9   18  21   16   7    1  19

[11282 rows x 11 columns]

In [33]:
# Find a way to create a model decifering which team won based on in game stats...  
# we're going to do this by creating a new dataframe with the stats above but with the game results from other dataframe


# split the dataframe into two so all results for winner aren't the same
df_1 = df_sig_team_stats.iloc[:2820,:]
df_2 = df_sig_team_stats.iloc[2820:,:]

# df 1 the winners are going to be team X
df_1 = df_1.rename(columns = {'WTeamID': 'XTeamID', 'WScore': 'XScore', 
                             'WFGM': 'XFGM', 'WFTM': 'XFTM',
                             'WFGM3': 'XFGM3', 'WFTA': 'XFTA',
                             'WDR': 'XDR', 'WAst': 'XAst',
                             'WTO': 'XTO', 'WBlk': 'XBlk',
                             'WPF': 'XPF', 'LTeamID': 'YTeamID',
                             'LScore': 'YScore', 'LFGM': 'YFGM',
                             'LFTM': 'YFTM', 'LPF': 'YPF',
                             'LFGM3': 'YFGM3', 'LFTA': 'YFTA',
                             'LDR': 'YDR', 'LAst': 'YAst',
                             'LTO': 'YTO', 'LBlk': 'YBlk',}) 
# df 2 winners are going to be team Y
df_2 = df_2.rename(columns = {'LTeamID': 'XTeamID', 'LScore': 'XScore', 
                             'LFGM': 'XFGM', 'LFTM': 'XFTM',
                             'LFGM3': 'XFGM3', 'LFTA': 'XFTA',
                             'LDR': 'XDR', 'LAst': 'XAst',
                             'LTO': 'XTO', 'LBlk': 'XBlk',
                             'LPF': 'XPF', 'WTeamID': 'YTeamID',
                             'WScore': 'YScore', 'WFGM': 'YFGM',
                             'WFTM': 'YFTM', 'WPF': 'YPF',
                             'WFGM3': 'YFGM3', 'WFTA': 'YFTA',
                             'WDR': 'YDR', 'WAst': 'YAst',
                             'WTO': 'YTO', 'WBlk': 'YBlk',})

In [35]:
# Combine the two dataframes and shuffle so the results are split 50/50 and random
df_combined = pd.concat([df_1, df_2])

# final dataframe named df for easy use
df = df_combined.iloc[np.random.permutation(len(df))].reset_index(drop=True)
df

df['X_Winner'] = (df['XScore'] > df['YScore']).astype(int)

df

,XTeamID,XScore,YTeamID,YScore,XFGM,XFGM3,XFTM,XFTA,XDR,XAst,...,YFGM,YFGM3,YFTM,YFTA,YDR,YAst,YTO,YBlk,YPF,X_Winner
0,1201,72,1461,83,27,5,13,19,20,13,...,28,17,10,13,24,23,17,4,20,0
1,1412,82,1368,72,31,6,14,22,26,16,...,28,7,9,16,23,14,12,2,19,1
2,1381,58,1470,75,18,2,20,24,15,7,...,29,1,16,20,19,15,15,2,23,0
3,1306,76,1136,95,26,8,16,18,21,10,...,36,11,12,12,24,18,6,10,14,0
4,1253,75,1414,80,31,7,6,10,24,13,...,28,11,13,13,23,14,10,5,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5636,1170,76,1225,78,30,7,9,16,27,10,...,19,8,32,41,16,9,9,2,16,0
5637,1200,64,1182,73,23,6,12,18,22,12,...,24,4,21,26,19,15,11,10,16,0
5638,1173,86,1250,62,28,14,16,23,32,21,...,24,8,6,11,23,14,4,2,18,1
5639,1449,79,1234,85,27,9,16,22,21,12,...,26,10,23,26,19,15,7,2,16,0
5640,1324,68,1297,53,24,9,11,12,22,7,...,20,7,6,12,12,10,9,2,13,1

In [37]:
df.columns

Index(['XTeamID', 'XScore', 'YTeamID', 'YScore', 'XFGM', 'XFGM3', 'XFTM',
       'XFTA', 'XDR', 'XAst', 'XTO', 'XBlk', 'XPF', 'YFGM', 'YFGM3', 'YFTM',
       'YFTA', 'YDR', 'YAst', 'YTO', 'YBlk', 'YPF', 'X_Winner'],
      dtype='object')

In [39]:
# Create dataframe with game results, but instead of in game stats, it's the average between the two...

merged_X_new = pd.merge(df, team_avg_df, left_on='XTeamID', right_on='Team', how='left')

# Merge YTeamID
merged_XY_new = pd.merge(merged_X_new, team_avg_df, left_on='YTeamID', right_on='Team', how='left', suffixes=('_X', '_Y'))

team_avg_df_with_game_results = merged_XY_new.drop(columns=[ 'XScore', 'YScore', 'XFGM', 'XFGM3', 'XFTM',
       'XFTA', 'XDR', 'XAst', 'XTO', 'XBlk', 'XPF', 'YFGM', 'YFGM3', 'YFTM',
       'YFTA', 'YDR', 'YAst', 'YTO', 'YBlk', 'YPF'])

final_df = team_avg_df_with_game_results

In [41]:
# split testing and training datasets
from sklearn.model_selection import train_test_split

X = final_df.drop(columns = 'X_Winner')
y = final_df['X_Winner']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=1227)

In [43]:
# Looking at feature importance one more time

from sklearn.ensemble import RandomForestClassifier

# Random Forest classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=1227)
rf_model.fit(X, y)

# Get feature importances
feature_importances = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

print(feature_importances)

    Feature  Importance
2   Score_X    0.072111
12  Score_Y    0.060975
13    FGM_Y    0.055331
3     FGM_X    0.052102
18    Ast_Y    0.051727
19     TO_Y    0.050032
17     DR_Y    0.049538
7      DR_X    0.048976
9      TO_X    0.048609
20    Blk_Y    0.046846
8     Ast_X    0.046305
10    Blk_X    0.043571
21     PF_Y    0.039307
6     FTA_X    0.038692
14   FGM3_Y    0.038138
5     FTM_X    0.037870
11     PF_X    0.037171
4    FGM3_X    0.037005
15    FTM_Y    0.036830
16    FTA_Y    0.036756
0   XTeamID    0.036678
1   YTeamID    0.035428

In [45]:
# drop some columns
# Keeping FGM3 because threes are getting more and more important in todays game of basketball
X = final_df.drop(columns = ['X_Winner', 'FTA_X', 'FTA_Y', 'FTM_Y', 'FTM_X'])
y = final_df['X_Winner']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=1227)

In [47]:
# Histogram based Gradient Boosting

from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import classification_report

list_learning_rate = [0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
# For loop to find optimal learning rate
for i in range(0,18):
    model = HistGradientBoostingClassifier(learning_rate=list_learning_rate[i])
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print('learning rate: ', list_learning_rate[i])
    print(classification_report(y_test, y_pred))

learning rate:  0.01
              precision    recall  f1-score   support

           0       0.63      0.71      0.67       549
           1       0.69      0.61      0.65       580

    accuracy                           0.66      1129
   macro avg       0.66      0.66      0.66      1129
weighted avg       0.66      0.66      0.66      1129

learning rate:  0.02
              precision    recall  f1-score   support

           0       0.64      0.72      0.68       549
           1       0.70      0.62      0.66       580

    accuracy                           0.67      1129
   macro avg       0.67      0.67      0.67      1129
weighted avg       0.67      0.67      0.67      1129

learning rate:  0.03
              precision    recall  f1-score   support

           0       0.65      0.72      0.68       549
           1       0.71      0.63      0.66       580

    accuracy                           0.67      1129
   macro avg       0.68      0.68      0.67      1129
weighted avg       0.68      0.67      0.67      1129

learning rate:  0.04
              precision    recall  f1-score   support

           0       0.65      0.72      0.68       549
           1       0.70      0.63      0.66       580

    accuracy                           0.67      1129
   macro avg       0.67      0.67      0.67      1129
weighted avg       0.67      0.67      0.67      1129

learning rate:  0.05
              precision    recall  f1-score   support

           0       0.65      0.71      0.68       549
           1       0.70      0.63      0.66       580

    accuracy                           0.67      1129
   macro avg       0.67      0.67      0.67      1129
weighted avg       0.67      0.67      0.67      1129

learning rate:  0.06
              precision    recall  f1-score   support

           0       0.64      0.72      0.68       549
           1       0.70      0.62      0.66       580

    accuracy                           0.67      1129
   macro avg       0.67      0.67      0.67      1129
weighted avg       0.67      0.67      0.67      1129

learning rate:  0.07
              precision    recall  f1-score   support

           0       0.65      0.71      0.68       549
           1       0.70      0.63      0.66       580

    accuracy                           0.67      1129
   macro avg       0.67      0.67      0.67      1129
weighted avg       0.67      0.67      0.67      1129

learning rate:  0.08
              precision    recall  f1-score   support

           0       0.65      0.72      0.68       549
           1       0.70      0.63      0.67       580

    accuracy                           0.67      1129
   macro avg       0.68      0.68      0.67      1129
weighted avg       0.68      0.67      0.67      1129

learning rate:  0.09
              precision    recall  f1-score   support

           0       0.65      0.71      0.68       549
           1       0.70      0.64      0.67       580

    accuracy                           0.67      1129
   macro avg       0.68      0.68      0.67      1129
weighted avg       0.68      0.67      0.67      1129

learning rate:  0.1
              precision    recall  f1-score   support

           0       0.65      0.72      0.68       549
           1       0.71      0.62      0.66       580

    accuracy                           0.67      1129
   macro avg       0.68      0.67      0.67      1129
weighted avg       0.68      0.67      0.67      1129

learning rate:  0.2
              precision    recall  f1-score   support

           0       0.64      0.69      0.66       549
           1       0.68      0.63      0.66       580

    accuracy                           0.66      1129
   macro avg       0.66      0.66      0.66      1129
weighted avg       0.66      0.66      0.66      1129

learning rate:  0.3
              precision    recall  f1-score   support

           0       0.65      0.70      0.67       549
           1       0.69      0.64      0.66       580

    accuracy                           0.67      1129
   macro avg       0.67      0.67      0.67      1129
weighted avg       0.67      0.67      0.67      1129

learning rate:  0.4
              precision    recall  f1-score   support

           0       0.64      0.70      0.67       549
           1       0.69      0.63      0.66       580

    accuracy                           0.67      1129
   macro avg       0.67      0.67      0.67      1129
weighted avg       0.67      0.67      0.66      1129

learning rate:  0.5
              precision    recall  f1-score   support

           0       0.64      0.70      0.67       549
           1       0.69      0.62      0.65       580

    accuracy                           0.66      1129
   macro avg       0.66      0.66      0.66      1129
weighted avg       0.66      0.66      0.66      1129

learning rate:  0.6
              precision    recall  f1-score   support

           0       0.62      0.70      0.66       549
           1       0.68      0.60      0.64       580

    accuracy                           0.65      1129
   macro avg       0.65      0.65      0.65      1129
weighted avg       0.65      0.65      0.65      1129

learning rate:  0.7
              precision    recall  f1-score   support

           0       0.63      0.70      0.66       549
           1       0.68      0.61      0.64       580

    accuracy                           0.65      1129
   macro avg       0.65      0.65      0.65      1129
weighted avg       0.65      0.65      0.65      1129

learning rate:  0.8
              precision    recall  f1-score   support

           0       0.64      0.70      0.67       549
           1       0.69      0.62      0.65       580

    accuracy                           0.66      1129
   macro avg       0.66      0.66      0.66      1129
weighted avg       0.66      0.66      0.66      1129

learning rate:  0.9
              precision    recall  f1-score   support

           0       0.64      0.69      0.66       549
           1       0.68      0.63      0.66       580

    accuracy                           0.66      1129
   macro avg       0.66      0.66      0.66      1129
weighted avg       0.66      0.66      0.66      1129

In [49]:
# use 0.1 (2/3rds is better than random guessing woohoo)
model = HistGradientBoostingClassifier(learning_rate=0.1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.65      0.72      0.68       549
           1       0.71      0.62      0.66       580

    accuracy                           0.67      1129
   macro avg       0.68      0.67      0.67      1129
weighted avg       0.68      0.67      0.67      1129

In [51]:
team_avg_df = team_avg_df.reset_index()

In [53]:
# Create dataframe with all possible matchups to predict every single one 
import itertools
matchups_df_new = pd.DataFrame(itertools.combinations(team_avg_df['Team'], 2), columns=['XTeamID', 'YTeamID'])

# Merge the team averages for the XTeamID and YTeamID
merged_X_new = pd.merge(matchups_df_new, team_avg_df, left_on='XTeamID', right_on='Team', how='left')
merged_XY_new = pd.merge(merged_X_new, team_avg_df, left_on='YTeamID', right_on='Team', how='left', suffixes=('_X', '_Y'))

df = merged_XY_new

In [55]:
df = df.drop(columns = ['FTA_X', 'FTA_Y', 'FTM_Y', 'FTM_X', 'Team_X', 'Team_Y'])

In [57]:
# get probability of first team winning
probabilities = model.predict_proba(df)
probability_x_wins = probabilities[:, 1]
df['Pred'] = probability_x_wins

In [59]:
df['ID'] = '2025_' + df['XTeamID'].astype(str) + '_' + df['YTeamID'].astype(str)
result_df = df[['ID', 'Pred']]

In [61]:
result_df

                   ID      Pred
0      2025_1101_1102  0.176694
1      2025_1101_1103  0.041473
2      2025_1101_1104  0.042221
3      2025_1101_1105  0.233680
4      2025_1101_1106  0.289913
...               ...       ...
66061  2025_1477_1479  0.120885
66062  2025_1477_1480  0.167443
66063  2025_1478_1479  0.455944
66064  2025_1478_1480  0.447213
66065  2025_1479_1480  0.461348

[66066 rows x 2 columns]

In [63]:
result_df.to_csv("Mens_Results2.csv", index = False)